/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_binghai_number2_Utils_SignUtil */

#ifndef _Included_site_binghai_number2_Utils_SignUtil
#define _Included_site_binghai_number2_Utils_SignUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_binghai_number2_Utils_SignUtil
 * Method:    getSign
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_site_binghai_number2_Utils_SignUtil_getSign
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
